""""""""
" Core "
""""""""

" disable vi compatibility mode
set nocompatible

" detect filetype
filetype on

" enable syntax highlighting
syntax on

" enable loading the plugin file for specific file types
filetype plugin on

" enable loading the indent file for specific file types
filetype indent on

" tell vim it's OK to use 256 colors at the terminal
set t_Co=256

" show matching brackets and parens
set showmatch

" use pop-up menu for tab completion of filenames
set wildmenu

" do not make backup~ files
set nobackup
set nowritebackup

" set character encoding to UTF-8
set encoding=utf-8

" show 3 lines above or below cursor when scrolling
set scrolloff=3

" show insert, replace, or visual mode in last line
set showmode

" show command in last line
set showcmd

set nowrap " don't wrap long lines

" turn on line numbers
set number  " leave off for now

" assumes fast connection
set ttyfast

" show line and column number
set ruler

" every window gets a status line
set laststatus=2

" set leader to comma
let mapleader = ","


"""" VIMRC 

" Reload vimrc configuration file
nnoremap <Leader>vr :source $MYVIMRC<CR>

" Open vimrc in a split
nnoremap <Leader>vs :vsp $MYVIMRC<CR>


"""" Searching

" Highlight matches in search
set hlsearch

" Turn off search highlight when done
nnoremap <Leader><Space> :nohlsearch<CR>


"""" To explore

" highlight the line the cursor is on
" set cursorline

" local leader to backslash. (local leader is used for only specific file
" types)
" let maplocalleader = "\\"

" list, listcharts (to show tab chars)
